FROM node:lts-alpine as build

WORKDIR /app

FROM nginx:stable-alpine as base

COPY ./dist /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

ENV NODE_ENV=development

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
